### ISSUE TITLE
[캐시] 회원은 본인의 캐시 사용 내역을 조회할 수 있습니다.

### ISSUE THREAD

**Issue by jyna120** [ssg-java3-240304/Ready-Auction#141]
## 🌈 Success criteria 
1. 회원은 본인의 캐시 사용 내역(전체, 입금, 출금)을 조회할 수 있습니다.
2. 캐시 사용 내역에는 충전, 출금, 결제, 환불의 경우가 있습니다.
3. 충전/환불은 + 파란색, 출금/결제는 - 빨간색으로 표시됩니다.

## 👷 To-do
- [x] TransactionDto 생성
- [x] SecurityContextHolder 사용하여 로그인한 사용자 정보 가져오기
- [x] Cash, Payment 조회하여 list에 각각 넣기
- [x] PaymentStatus 필터링 - Completed 결제 완료와 Rollback_Completed 환불 완료인 것만 넣기
- [x] Payment 조회 시 사용자가 구매자일 경우와 사용자가 판매자일 경우 각각 다르게 넣기
- [x] 날짜 기준으로 내림차순 정렬
