### ISSUE TITLE
NCP DB 서버 생성 및 연결

### ISSUE THREAD

**Issue by yeahjinjeong** [ssg-java3-240304/Ready-Auction#16]
## 🌈 Success criteria 

1. profile로 스프링앱 관리하기
2. 운영환경에 맞도록 CI/CD 작성하기
3. ncp DB 서버 생성 및 연결

## 👷To-do

- [ ] 개발환경 test profile 적용하기
- [ ] 운영환경 prod profile 적용하기
- [ ]  운영 DB관련 정보가 노출 되지 않도록 Github Secret으로 관리하기
- [ ] Docker Image Build시에 Secret 적용할수 있도록 Dockerfile 작성하기
- [ ] Github Action workflow에 Secret 적용하기
