### ISSUE TITLE
[경매] 경매 상품 상태는 업데이트 됩니다.

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/Ready-Auction#175]
## 🌈 Success criteria

1. 경매 종료 후 경매 상태가 올바르게 업데이트돼야 합니다. 

## 👷 To-do

- [x] 경매 종료시(상품 결제를 진행한 이후 ) 상품 Status를 END로 수정
- [x] 경매 시작시 상품 Status를 START로 수정
- [x] 경매품에 입찰자가 생길 시 Status를 PROGRESS로 수정
