### ISSUE TITLE
[경매] 입찰,즉시구매, 결제, 구매확정  생성시 동시성 문제가 발생할 수 있으니 이를 해결해야합니다.

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/Ready-Auction#177]
## 🌈 Success criteria

1. 여러 사용자가 동시에 같은 상품에 입찰할 때 발생하는 동시성 문제가 있습니다. 이는 입찰 생성 과정에서 데이터 일관성이 깨질 수 있는 상황을 초래할 수 있습니다.

## 👷 To-do

- [x] 여러 사용자가 동시에 입찰해도 데이터 정합성이 보장됩니다.
- [x]  하나의 경메에 결제, 즉식구매, 구매확정에 동시에 여러 요청이 와도 데이터의 정합성이 보장 됩니다
- [x] 동시성 문제를 해결할 수 있는 로직이 도입됩니다.
- [x]  레디스의 분산락을 이용해서 실시간 입찰의 동시성을 관리했다.

**Comment by ooANAoo** [comment]
문제의 시작  (  레디스 락 획득 및 해제 시간이 너무 느리다. )
-레디스 Wait Time 과 Lease Time을 너무 짧게 잡은 나머지 동시성이 제데로 처리 되지않았다.
- 한 경매로 총 15개의 결제 요청을 동시에 보냈다. 한개의 결제만 승인돼야하지만 여러게의 결제가 승인됐다.
- 적절한 시간을 정하기 위해 테스트 진행

데이터 베이스 서비스 처리시간
- 최소 실행 시간: 200.8406 milliseconds
- 최대 실행 시간: 290.1311 milliseconds

레디스 락 획득 - 데이터 베이스 서비스 처리 - 레디스 락 헤제 동안 처리 시간
- 최소 실행 시간: 2782.8406 milliseconds
- 최대 실행 시간: 9899.1311 milliseconds
이 결과를 보면, 락획득 및 해제 시간에 많은 시간이 소요됨을 알  수 있음.

3. 문제점 분석
- 레디스 캐쉬 서버의 성능문제
- 레디스 서버의 나라 설정 문제

4. 제안 및 해결책
- 금전적인 문제로 레디스 무료를 써야하기에 성능문제는 해결할 수없음
- 나라를 확인했더니 us미국으로 설정돼있었음 -> 서울리전으로 수정

5. 결과
 락 획득 - 데이터베이스 서비스 로직 실행 - 락 해제 동안 걸리는 시간
- 최소 실행 시간: 276.3225 milliseconds
- 최대 실행 시간: 1376.1129milliseconds
최초 락 획득시 시간이 대폭 감소 돼서 데이터베이스 서비스 로직만 처리하는 시간과 비슷하게 걸리는것을 확인할수있었다.
다만 동시에 락 요청이 증가할 수록 , 서버에 부하 떄문인지 시간이 기하급수적으로 증가한다...


대용량 처리에는 적 합 하지 않은 방식일 수 있음....

**Comment by ooANAoo** [comment]
레디스 락 획득  waitTime, leaseTime 적절한 값 설정하는법.

입찰,즉시구매, 결제, 구매 확정  모두 같은 락 id를 가진 여러 요청 중  첫 요청에 대한 동시성만 잡히면 이후의 요청들은 전부 파기 시켜야하기 때문에 waitTime을 최소화해서 롤백 연산을 최소화 했습니다.

최초 락 획득 - 데이터베이스 로직 싱행 - 락 헤제 시   최대 1초가 걸리 때문에
leaseTime은 안전성을 위해 3초로 했고,
waitTime은 leaseTime의 1.5배로 했습니다

**Comment by ooANAoo** [comment]
즉시구매 시 이메일 보내는 코드가 트랜젝셔널 키워드가 붙어 있는 db 로직 처리 함수 내에 있을 땐 동시성 이슈가 발생했지만. 
 트랜잭셔널 윗 단으로 ,밖으로 뺴니까 문제가 없어짐.
 
 수정전 이메일 보내는 코드위치
  @Transactional
    public Product createWinner(WinnerDto winnerDto) {
        try {
            // Winner 객체를 생성하고 제품에 설정
            Winner winner = Winner.builder()
                    .memberId(winnerDto.getUserId())
                    .status(PurchaseStatus.CONFIRMED)
                    .price(winnerDto.getWinnerReqDto().getBuyPrice())
                    .winnerTime(winnerDto.getWinnerReqDto().getBuyTime())
                    .category(winnerDto.getWinnerReqDto().getCategory())
                    .build();
            winnerDto.getProduct().setWinner(winner);
            winnerDto.getProduct().setAuctionStatus(AuctionStatus.END);
            winnerDto.getProduct().setCurrentPrice(winnerDto.getWinnerReqDto().getBuyPrice());
            log.info("Winner created successfully for product ID: {}", winnerDto.getProduct().getId());

            // 제품을 저장
            Product savedProduct = productRepository.save(winnerDto.getProduct());

            EmailMessage emailMessage = EmailMessage.builder()
                    .to(email)
                    .subject("Congratulations! You have won the auction.")
                    .message("<html><head></head><body><div>" + productDto.getName() + " auction was won by you. Please visit our website to complete the payment.</div></body></html>")
                    .build();
            emailService.sendMail(emailMessage);
            if (savedProduct == null) {
                throw new RuntimeException("Failed to save the product with the winner");
            }

            return savedProduct;
        } catch (DataAccessException e) {
            // 데이터베이스 관련 예외 처리
            throw new RuntimeException("Database error during saving the product with the winner: " + e.getMessage(), e);
        } catch (Exception e) {
            // 기타 예외 처리
            throw new RuntimeException("Unexpected error occurred during creating the winner: " + e.getMessage(), e);
        }
    }

 수정 이후 이메일  코드 위치
   public ProductDto winnerLock(String email, WinnerReqDto winnerReqDto) {
        String lockKey = String.format("Product:productId:%d", winnerReqDto.getProductId());
        return redisLockService.executeWithLock(lockKey, 30, 30, TimeUnit.SECONDS, () -> {
            Long userId = memberService.findByEmail(email).getId();
            if (!productService.findById(winnerReqDto.getProductId()).get().hasWinner()) {
                PaymentReqDto paymentReqDto = PaymentReqDto.builder()
                        .productId(winnerReqDto.getProductId())
                        .payTime(winnerReqDto.getBuyTime())
                        .amount(winnerReqDto.getBuyPrice() / 10)
                        .category(PaymentCategory.BID)
                        .build();

                paymentService.createBidPayment(userId, paymentReqDto);
                ProductDto productDto = productService.startWinnerProcess(email, winnerReqDto);
                EmailMessage emailMessage = EmailMessage.builder()
                        .to(email)
                        .subject("Congratulations! You have won the auction.")
                        .message("<html><head></head><body><div>" + productDto.getName() + " auction was won by you. Please visit our website to complete the payment.</div></body></html>")
                        .build();
                emailService.sendMail(emailMessage);
                return productDto;
            } else {
                throw new RuntimeException("The product has already been won");
            }
        });
    }
