### ISSUE TITLE
[경매]상품이미지를 데이터베이스에서 프론트엔드로 넘겨줍니다.

### ISSUE THREAD

**Issue by dohwani** [ssg-java3-240304/Ready-Auction#179]
## 🌈 Success criteria 

1. 회원은 경매상세 페이지에서 상품이미지를 확인 할 수 있습니다.

## 👷 To-do

- [x] product 테이블에서 imgurl을 가져옵니다.
- [x] view단에서 타임리프로 imgurl을 보여줍니다. 
- [x] 여러개의 imgurl을 보여주기 위하여 javascript를 사용하여 네비게이션바를 추가합니다.
