### ISSUE TITLE
[경매] 백단의 경매마감시간을 기준으로 현재시간과 비교후 남은시간으로 타이머를 설정합니다.

### ISSUE THREAD

**Issue by dohwani** [ssg-java3-240304/Ready-Auction#180]
## 🌈 Success criteria 

1. 경매상세 페이지에서는 경매 마감 시간을 타이머 형식으로 보여줍니다.
2. 스케줄러를 통해 경매마감을 처리합니다.
3. 

## 👷 To-do

- [x] product 테이블에서 endtime을 가져옵니다.
- [x] 현재시간- endtime으로 남은시간을 계산합니다.
- [x] 남은시간을 타이머형식으로 보여줍니다.
- [x] 1분마다 스케줄러가 돌아가면서 마감시간에 다다른 경매를 조회한 후 최고입찰 자를 낙찰자로 선정하고 메일을 보냅니다.
- [x] 기존 스케줄러 아키텍처에서 -> 레디스 ttl기능을 이용한 경매마감으로 기능이 수정 됐습니다.
- [x] 레디스 ttl설정 후 productId를 저장하는 producer 제작
- [x] 레디스 ttl 이 expire 시 해당 이벤트를 받아오는 listener 제작
- [x] expire 이벤트 리슨 한 이후 경매를 마감 시키는 endAuction제작
