### ISSUE TITLE
[경매] 구매자는 상품을 결제 할 수 있습니다.

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/Ready-Auction#185]
## 🌈 Success criteria

1. 결제 시 구매자는 플랫폼으로 포인트를 지불합니다. 단 이 때 판매자는 아직 대금을 받지 못합니다.
2. 결제 실패시 경매 상품의 상태값 롤백 

## 👷 To-do

- [x] 결제 성공 시 구매자 계좌에서 해당금액만큼 출금합니다. 
- [x] 결제 성공 시 Winner의 Status를 CONFIRMED -> IN_PROGRESS로 수정합니다.
- [x] 결제 성공 시 payment 기록이 만들어집니다.
- [x] 결제 성공 시 payment Status를 PROCESSING으로 저장합니다.
