### ISSUE TITLE
[경매] 경매 마감

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/Ready-Auction#186]
## 🌈 Success criteria

1. 1분마다 경매 상품 목록을 조회하면서 마감시간인 경매에서 낙찰 자를 선정하고 경매를 종료합니다.

## 👷 To-do

- [ ] Spring Scheduler를 이용해서 1분마다 경매 마감 메서드 실행
- [ ] 경매 상품중 마감시간인 리스트 검색
- [ ] 경매 마감 리스트에서 각 경매 마다 입찰금이 가장 높은 입찰자들을 필터링.
- [ ] 해당 마감 경매들의 최고가 입찰자들을 각각 경매의 낙찰자로 선정하기
- [ ] 낙찰자로 선정됐다고, 알림 날리기.
