### ISSUE TITLE
[경매]구매자는 대금 불이행 시 패널티를 지불합니다.

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/Ready-Auction#189]
## 🌈 Success criteria

1. 낙찰자로 선정되고 대금을 지불하지않으면, 페널티(즉시 구매가의 10퍼)
2. 대금 입금 기한 3일.
## 👷 To-do

- [x] 하루에 한번 Scheduler를 통해 대금 미지불 구매자들에게 패널티 부과
- [x] 레디스ttl기능을 이용해 결제 대금 이행기간인 3일은 넘어도 결제를 하지않은 구매자들에게 패널티 부과
- [ ] 패널티 알림 보내기
