### ISSUE TITLE
[알림] 구매자는 알림을 받을 수 있습니다.

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/Ready-Auction#192]
## 🌈 Success criteria

1. 경매가 시간이 마감 돼 ,낙찰자로 선정 될 시 결재 요구 알림을 받는다.
2. 경매가 종료되고, 비낙찰자가 될 시 경매가 종료됐다는 알림을 받는다.
3. 결제를 안 할 시 패널티 알림을 받는다.

## 👷 To-do

- [x] Scheduler를 통한 경매 마감 시 낙찰자로 선정된 구매자에게 결제 요구 알림을 보낸다. 
- [x] Scheduler를 통한 경매 마감 시, 비낙찰자가 된 입자자들 에게 경매가 종료 됐다는 알림을 보낸다.
- [ ] 하루에 한번 Scheduler를 통해 구매자를 점검해서, 결제를 안할 시 패널티 알림을 보낸다.
- [ ] 알림 페이지를 구현
