### ISSUE TITLE
[경매] ui는 유저와의 상호작용 해야합니다.

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/Ready-Auction#193]
## 🌈 Success criteria

1. 입찰, 낙찰 이 불가능 하면 버튼도 누를 수 없게 바껴야한다 .
2. 상품을 등록하면, 상품 검색 페이지로 이동하도록 
3. 결제하면 버튼 누를 수 없게 바껴야한다. 
4. 구매확정하면 버튼 누를 수 없게 바껴야한다. -> 다른 페이지로 이동
5.  결제, 구매확정 페이지 는 액션이 끝나면 해당 주소로 다시 가도 아무런 페이지가 안뜨도록 수정할것.

## 👷 To-do

- [ ] 입찰, 낙찰 이 불가능 하면 버튼도 누를 수 없게 바껴야한다 .
- [ ] 상품을 등록하면, 상품 검색 페이지로 이동하도록 
- [ ] 결제하면 버튼 누를 수 없게 바껴야한다. 
- [ ] 구매확정하면 버튼 누를 수 없게 바껴야한다. -> 다른 페이지로 이동
- [ ] 결제, 구매확정 페이지 는 액션이 끝나면 해당 주소로 다시 가도 아무런 페이지가 안뜨도록 수정할것.
