### ISSUE TITLE
[추가 사항] 

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/Ready-Auction#223]
## 🌈 Success criteria

짜잘한 추가사항을 모두 통틀어서 적기

## 👷 To-do

- [x] 상품 상세에서 현재 입찰가가 실시간으로 바뀌는 것 눈에 띄게 하기
- [ ] 상품 상세 페이지에 현재 입찰자 수 몇 명인지 띄우기
- [x] 상품 업로드 시 상품 조회로 리다이렉트
- [x] 최초 입찰 시 입찰금 지불 된다는알림
- [ ] 최초 입찰 시 돈 없으면 돈없어서 입찰 실패했다고 알리기 
- [x] 즉시 구매시 주의 알림. 즉시 날찰 된다고
- [ ] 상품 등록 시 즉시구매가가 입찰가보다 낮은 경우 상품을 등록할 수 없다
- [x] 즉시 구매를 눌렀으면, 결제하기 안누르고 뒤로가면 3일 이후에 경매 닫기
      -> PaymentStatus에 OUTSTANDING (미결제) 추가하기 - 결제 안 하고 경매가 닫힌 경우
      -> 구매자의 선입금 중 70%는 판매자, 30%는 관리자에게 돌아간다. 구매자는 선입금을 환불받을 수 없다.
      -> 구매자가 아닌 다른 입찰자들은 선입금을 환불받을 수 있다.
- [x] 상품등록 할 때 상품 수정할 수 없다고 알림 띄우기
- [x] 경매 시간이 설정한 시간 보다 8시간 후로 설정됨
- [ ] 이메일 인증
- [x] 이메일 중복 검사
- [x] 닉네임 중복 검사
- [ ] 로그인 시 성공 여부 알림으로 알리기
- [x] 낙찰 성공시 마이페이지 - 낙찰품으로 연결 -> 지영 해결
- [ ] 구매자가 아닐 시 url로 auctionDetails나 결제, 구매 확정 페이지 링크 치면 못 들어가게 막기
- [x] 구매 확정 버튼 누르고나서 상품 목록 조회로 리다이렉트
- [x] /auction/auction을 /auction으로 바꾸기 -> 지영 해결
- [x] 상품 목록에 이미지 크기 통일하게 하기. 이미지 크기가 달라서 박스가 제각각
- [x] 즉시구매, 결제 시 로딩 화면 넣기. 다른 땐 다 제거
- [x] 상품 등록 작성 중 등록하지 않고 뒤로가기 할 경우 서버에 올린 이미지 삭제하기
- [x] 상품 등록 중 기간 선택 시 눈에 띄게 하기
- [ ] #290
- [ ] 게시글 신고 받으면 관리자가 게시글 삭제하게 하기
- [ ] 신고 당한 회원은 로그인 시 사이트 이용할 수 없다 하게 하기
- [ ] 관리자로 로그인하면 관리자 페이지를 제외한 모든 것 (입찰, 채팅 등) 막기
- [ ] 인덱스 홈페이지 만들기
- [ ] 프론트 다듬기
- [ ] System.out.println(); 출력문 다 지우기
- [x] 상대 주소를 다 절대 주소로 바꾼 후 context-path에 /app 제거하기, 찜하기 버튼 제거
- [x] 신고 깃발 눌러야 드롭다운 되게 변경
- [ ] 게시글 신고 시 본인 게시글은 신고 불가능하게 하기
- [ ] 문의하기 작성 후 완료 누르면 완료되었다는 팝업
- [ ] 통계관리에서 아래 더 보고 싶은데 어떻게 봐야할지 모르겠습니다
- [x] 관리자로 로그인하면 마이페이지 안 들어가짐
- [x] 경매 완료시 사이트가 먹는 수수료는 따로 없는지? 안전거래 시스템 제공에 있어서의 수익구조는?
- [ ] 채팅은 header title이 title이고, 우리 로고도 안 붙는다
- [ ] 경매 부분 금액에 쉼표 붙이기
- [ ] system.out.println 제거 -> log.info로 변경
- [ ] 코드 최적화
- [ ] 주석 달기

**Comment by jyna120** [comment]
- 즉시 구매를 눌렀으면, 결제하기 안누르고 뒤로가면 3일 이후에 경매 닫기
-> 결제를 안 해서 경매가 닫히면 그 사람한테 패널티를 줘야하지 않을까? 선입금 환불을 막는다거나

- 선입금 환불 시기 조절. 누군가 즉시 구매하기를 누르면 바로 선입금이 환불 되게
-> a랑 b가 입찰함. 그런데 a가 즉시 구매하기 누르면 거기서 바로 선입금 환불되는 걸로 바꿔야 할 것 같아. a가 결제를 해야만 a와 b 둘 다 선입금이 환불 돼. a가 계속 결제를 안 하면 b의 선입금이 계속 환불이 안 돼..
