### ISSUE TITLE
[채팅] 사용자는 채팅방에서 거래할 상품 정보 및 판매자/구매자 프로필 정보를 확인할 수 있습니다.

### ISSUE THREAD

**Issue by yeahjinjeong** [ssg-java3-240304/Ready-Auction#25]
## 🌈 Success criteria 

1. 상품 보러가기를 눌러 상세 페이지로 이동합니다.
2. 상대방의 프로필을 눌러 프로필 상세 페이지로 이동합니다.

## 👷 To-do

- [x] 거래할 상품 정보를 확인할 수 있습니다.
- [x] 판매자/구매자 프로필 정보를 확인할 수 있습니다. 클라이언트에서 세션의 멤버아이디와 비교하여 내가 판매자일 경우 구매자의 프로필을, 내가 구매자일 경우 판매자의 프로필을 출력합니다.
- [x] 구매확정할 수 있습니다
- [x] 상품 디테일 페이지로 이동할 수 있습니다

## 🧶 Review

- [x] 구매 확정시 구매확정하지 못하게 하기
