### ISSUE TITLE
[채팅] 사용자는 대화 상대의 매너를 평가할 수 있습니다.

### ISSUE THREAD

**Issue by yeahjinjeong** [ssg-java3-240304/Ready-Auction#27]
## 🌈 Success criteria 

1. 채팅방 내 상단에서 매너평가를 할 수 있습니다.
2. 매너평가를 클릭할 시에 매너평가 등록폼으로 이동합니다.

## 👷 To-do

- [ ] 해당 프로필의 정보를 함께 전달합니다.
- [x] 이넘 리스트를 갖는 매너 엔티티를 생성합니다.
- [ ] 폼의 post 요청을 매너평가 DTO로 받습니다. 이때 해당 프로필의 정보도 함께 받습니다.
- [x] 전달받은 서버는 MemberId를 조회하여 매너스코어를 변경합니다.

## 🧶 Review

기본 점수 50점
좋아요 하나에 5점
싫어요 하나에 5점
체크 개수는 관련없음
