### ISSUE TITLE
[테스트] - 테스트를 통해 찾은 오류를 해결합니다.

### ISSUE THREAD

**Issue by seongyeongit** [ssg-java3-240304/Ready-Auction#277]
## 🌈 Success criteria

1. 테스트를 통해 찾은 오류를 해결합니다.

## 👷 To-do

- [x] 상대 주소를 다 절대 주소로 바꾼 후 context-path에 /app 제거하기, 찜하기 버튼 제거
- [x] 신고 깃발 눌러야 드롭다운 되게 변경
- [ ] 게시글 신고 시 본인 게시글은 신고 불가능하게 하기
- [ ] 문의하기 작성 후 완료 누르면 완료되었다는 팝업
- [ ] 통계관리에서 아래 더 보고 싶은데 어떻게 봐야할지 모르겠습니다
- [x] 관리자로 로그인하면 마이페이지 안 들어가짐
- [ ] 경매 완료시 사이트가 먹는 수수료는 따로 없는지? 안전거래 시스템 제공에 있어서의 수익구조는?
- [ ] 채팅은 header title이 title이고, 우리 로고도 안 붙는다
