### ISSUE TITLE
[마이페이지] 회원은 회원 탈퇴를 할 수 있습니다.

### ISSUE THREAD

**Issue by jyna120** [ssg-java3-240304/Ready-Auction#31]
## 🌈 Success criteria 

1. 회원은 회원 탈퇴를 할 수 있습니다.
2. 회원 탈퇴하기를 선택시 계정 삭제하기 페이지로 넘어갑니다.
3. 계정 삭제 재확인 및 계정 삭제 시 경고 안내 메세지가 출력됩니다.
4. 안내 메시지 하단에서 계정 삭제 이유를 드롭 다운 메뉴에서 선택합니다..
5. 계정 삭제 이유 선택 시 하단에 안내 메세지와 회원 탈퇴 재확인 버튼이 나타납니다.
6. 회원 탈퇴 재확인 버튼은 2개 입니다.

## 👷 To-do

- [ ] 회원은 회원 탈퇴를 할 수 있습니다.
- [ ] 회원 탈퇴하기를 선택시 계정 삭제하기 페이지로 넘어갑니다.
- [ ] 계정 삭제 재확인 및 계정 삭제 시 경고 안내 메세지가 출력됩니다.
- [ ] 안내 메시지 하단에서 계정 삭제 이유를 드롭 다운 메뉴에서 선택합니다.
- [ ] 계정 삭제 이유 선택 시 하단에 안내 메세지와 회원 탈퇴 재확인 버튼이 나타납니다.
- [ ] 회원 탈퇴 재확인 버튼은 2개 입니다.
