### ISSUE TITLE
[마이페이지] 회원은 본인의 경매 등록 내역을 조회할 수 있습니다.

### ISSUE THREAD

**Issue by jyna120** [ssg-java3-240304/Ready-Auction#32]
## 🌈 Success criteria 
1. 회원은 본인이 등록하여 판매 중/거래 완료/유찰된 경매 내역을 조회할 수 있습니다.
2. 상품명 클릭 시 경매 글로 이동합니다.
3. 유찰된 경매 내역은 입찰 기간이 끝난 후 입찰자가 없을 경우이므로 숨기기를 할 수 있습니다.

## 👷 To-do
- [x] 판매 중 - Product 엔티티에서 memberId가 일치하는 productId 중 auctionStatus가 START 또는 PROGRESS인 경우
- [x] 거래 완료- Payment 엔티티에서 memberId가 일치하는 productId 중 paymentStatus가 COMPLETED인 경우
- [x] 유찰 - Product 엔티티에서 memberId가 일치하는 productId 중 auctionStatus가 END이고, Bid 엔티티에서 일치하는 productId가 없는 경우 (해당 상품에 대해 입찰 내역이 없는 경우)
