### ISSUE TITLE
[서버] NCP Object Storage 버킷 생성 및 연결

### ISSUE THREAD

**Issue by jyna120** [ssg-java3-240304/Ready-Auction#36]
## 🌈 Success criteria 
1. NCP 서버를 사용하여 파일 서버를 구축할 수 있습니다.

## 👷To-do
- [x] NCP Object Storage 버킷 생성
- [x] 파일 업로드 구현
- [x] 파일 불러오기 구현
