### ISSUE TITLE
NCP서버 CICD 구축 및 index페이지 연결

### ISSUE THREAD

**Issue by jyna120** [ssg-java3-240304/Ready-Auction#4]
## 🌈 Success criteria
1. NCP 서버를 사용하여 CICD를 구축할 수 있습니다.

## 👷To-do
- [x] NCP 서버 생성
- [x] rocky linux에서 docker 설치
- [x] docker-image.yml 생성
- [x] Github Actions - secrets, variables 생성
- [x] build - deploy
