### ISSUE TITLE
[경매] 회원(판매자)은 판매할 상품을 등록할 수 있습니다.

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/Ready-Auction#45]
## 🌈 Success criteria 

[사진 등록]	
- 회원(판매자)은 판매할 상품의 사진을 등록할 수 있습니다.
- 상품 등록 페이지에 사진 속에는 반드시 옷 태그가 꼭 나오게 찍어야 합니다. 규제에 맞지 않는 글은 삭제될 수 있습니다.

[카테고리 설정]	
- 회원(판매자)은 판매할 상품의 카테고리를 선택할 수 있습니다.
- 카테고리에는 스포츠별(축구,농구,야구)->국내/해외->리그별(스포츠별 상이)->팀명이 있습니다.
- 카테고리는 필수로 선택해야 합니다.

[상품명 등록]	
- 회원(판매자)은 판매할 상품의 이름을 설정할 수 있습니다.
- 상품명은 필수로 입력해야 합니다.

[상품 설명 등록]
- 회원(판매자)은 상품 정보를 등록할 수 있습니다.
- 회원(판매자)은 판매할 상품을 등록할 수 있습니다.
-  상품 등록을 누르면 밑에 안내 사항을 볼 수 있습니다.

[경매 마감 시간 설정]
- 회원(판매자)은 판매할 상품의 경매 마감 시간을 선택할 수 있습니다.
- 경매 마감 시간은 1일/3일/5일/7일이 있습니다.
- 상품 등록 순간부터 마감 시간이 적용됩니다.
- 경매 마감 시간은 필수로 설정해야 합니다.

[경매 시작가 설정]	
- 회원(판매자)은 경매 시작가 (최저희망가)를 설정할 수 있습니다.
- 경매 시작가는 숫자만 입력 가능합니다.
- 경매 시작가는 필수로 입력해야 합니다.

[입찰 단위 설정]	
- 회원(판매자)은 입찰 단위를 선택할 수 있습니다.
- 입찰 단위는 판매자 재량으로 직접 입력 할 수 있습니다.
- 입찰 단위는 숫자만 입력이 가능합니다.
- 입찰 단위는 필수로 선택해야 합니다.

[즉시 구매가 설정]	
- 회원(판매자)은 즉시 구매가 (최고희망가)를 설정할 수 있습니다.
- 즉시 구매가는 숫자만 입력이 가능합니다

## 👷To-do

- [ ] 사진 등록
- [ ] 카테고리 설정
- [ ] 상품명 등록
- [ ] 상품 설명 등록
- [ ] 경매 마감 시간 설정
- [ ] 경매 시작가 설정
- [ ] 입찰 단위 설정
- [ ] 즉시 구매가 설정

**Comment by ooANAoo** [comment]
상품 등록 로직

유저가 상품 정보를 적는중에 이미지를 올리면 이미지는 상품등록과별계로 비동기로 서버에 바로 업로드됨. 이후 이미지가 정상적으로 등록됐으면 클라이언트에게 알림이가고, 클라이언트는 해당 이미지 주소를 전달 받음. 이후 해당 이미지와 나머지 설명을 다적었으면 상품등록을 누르고 해당 이미지 주소를 포함함, 상품정보가 서버로보내짐.



지금 문제점
1. 상품 이미지 등록하다가 클라이언트가 새로고침을 하거나 다른거를 하러가도 이미지는 서버에 올라간다...
2. 한번 서버에 올라간 이미지는 다시 올릴수 없다. 이미 있으면 해당 주소를 반환하게 바꿔야 할듯.
3.   이미지가 안올라가져도 게시글은 올릴수있다.
