### ISSUE TITLE
[경매] 회원은 검색을 통해 찾고자 하는 물건을 검색할 수 있습니다.

### ISSUE THREAD

**Issue by seongyeongit** [ssg-java3-240304/Ready-Auction#49]
## 🌈 Success criteria 

1. 추천 검색어 기능이 있습니다.
2. 한 글자라도 포함된 게시물이 있다면 검색이 가능합니다.

## 👷To-do

- [x] 추천 검색어 기능이 있습니다.
- [x] 한 글자라도 포함된 게시물이 있다면 검색 가능합니다.
- [x] 경매 상태가 END인 건에 대해서 보이지 않게 합니다.

**Comment by seongyeongit** [comment]
![Image](https://github.com/user-attachments/assets/8385cdb5-22ab-4cca-bf2a-fcd726ff02e6)

-> like 연산으로 게시물이름과 같은 글자가 한 글자라도 있으면 추천검색어로 확인(스크롤)
